### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by BugsBunnyBR** [kissmetrics/KISSmetrics-Android-SDK#1]
Hi, I would like to know how to compile the project? The API folder does not seems to be a valid project since it has the android class loader in the path, but does not have the AndroidManifest.xml or project.properties.

For now, I moved the API files from KISSmetricsAPI/src/com/kissmetrics/  to KISSmetricsAPIIntegration/src/com/kissmetrics/
and imported the Android project.

**Comment by healyk** [comment]
We have converted the project to Gradle.  You should be able to build it using the gradle command line or Android Studio.

I've also included an `AndroidManfiest.xml` file in the src root.

Reopen if you have any problems building the library.
