### ISSUE TITLE
Gradle repository ?

### ISSUE THREAD

**Issue by emich** [kissmetrics/KISSmetrics-Android-SDK#16]
I am using Android Studio and would like to integrate the Kissmetrics SDK using a dependency in my build.gradle file. The SDK as present here needs to be imported by either adding the classes to my project or create a library project.

**Comment by healyk** [comment]
I've pushed the library to the JCenter repo.  You can include it with:

```groovy
dependencies {
  compile 'com.kissmetrics.sdk:KISSmetricsSDK:2.2.2'
}
```

If you don't already have `jcenter` in your `repositories` also include it:

```groovy
buildscript {
  repositories {
    jcenter()
  }
}
```

Let me know if you have any problems with this.
